package com.mogawe.mosurvei.model.store;

public enum PrefKey {

    ID_USER,
    SENT_GCM_TOKEN_TO_SERVER,
    SENT_GUEST_GCM_TOKEN_TO_SERVER,
    IS_LOGGED_IN,
    LOGGED_IN_AS,
    CERTIFICATE_AFTER_LOGIN,
    TOKEN,
    PASS,
    IS_PHONE_ACTIVE,
    IS_HAVE_PASSWORD,

    IS_TRY_GAWEAN,
    IS_ALREADY_TRY,

    IS_PAGE_ACTIVE,
    IS_NOT_FIRST_BUILDING_STORE_COUNT,
    IS_NOT_FIRST_ROAD_STORE_COUNT,
    IS_NOT_FIRST_INBUILDING_STORE_COUNT,
    IS_NOT_FIRST_LAUNCH,

    ACTIVATION_CODE,
    TIMER_RESEND,

    MY_LOCATION,
    TRACKER_INTERVAL,

    UPDATE_AVAILABLE,
    NEXT_NEAR_JOB_NOTIFICATION_TIMESTAMP,
    IS_EVER_REFRESH,
    IS_SHOW_GAWEAN,
    IS_REFRESH_GAWEAN,
    IS_GAWEAN_SPOTLIGHT_SHOW,
    IS_POINT_SPOTLIGHT_SHOW,
    IS_BALANCE_SPOTLIGHT_SHOW,
    IS_GAWEAN_DONE_SPOTLIGHT_SHOW,
    IS_PROFILE_NAME_SPOTLIGHT_SHOW,

    IS_NEED_FORCE_REFRESH_HOME,
    IS_CAMERA_CHANGED,
    IS_OFFLINE,
    IS_UPDATE_FACING_ITEM,
    REVISION_VERSION,
    IS_NOTIF_AVAILABLE,


    CERTIFICATE,
}
